version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: loan-management-broker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    image: postgres
    container_name: loan-management-db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=django
      - POSTGRES_DB=loan-management
    ports:
      - 54321:5432