version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: loan-management-broker
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  postgres:
    image: postgres
    container_name: loan-management-db
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=django
      - POSTGRES_DB=loan-management
    ports:
      - 54321:5432
  django:
    build: ./server
    container_name: loan-management-server
    ports:
     - 8000:8000
    depends_on:
      - postgres
    command: python manage.py runserver 0.0.0.0:8000
  celery:
    build: ./server
    container_name: loan-management-celery
    depends_on:
      - postgres
      - rabbitmq
    command: python -m celery -A loan_management worker
  ui:
    build: ./client-ui
    container_name: loan-management-ui
    depends_on:
      - django
    ports:
      - 5173:5173
