# Generated by Django 4.2.2 on 2023-06-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('D', 'Negado')], default='P', max_length=1)),
                ('metadata', models.JSONField(verbose_name='Campos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Proposta',
            },
        ),
        migrations.CreateModel(
            name='ProposalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=200, verbose_name='Nome')),
                ('enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
            ],
            options={
                'verbose_name': 'Campo',
            },
        ),
    ]
